### PR TITLE
Define how documents can be updated in this repository

### PR DESCRIPTION
**Pull request by TheAspens**

### CODE REVIEW

**Comment by Uplinger** [comment]
I think the changes to these look good and help define structure for the future well.  Thanks.

**Comment by ballen4705** [comment]
This may not be the correct place for this comment.  But IMO section 4  ("Contribution Process") should also list "Management" as  a way to contribute to BOINC.  This can include managing a development group, managing a BOINC project, or managing the PMC.

**Comment by TheAspens** [comment]
@ballen4705 - I think your comments are valid and valuable.  However, I think that they should be submitted as a change separate from this currently proposed change since they involve different topics and parts of the governance document.  Let me know if you need help setting up the proposal as a pull request (Oliver or Bernd could help as well).

**Comment by TheAspens** [comment]
Approved by the PMC with a vote of 6-0.  See https://groups.google.com/forum/#!topic/boinc_admin/yxxHcH4Uxkc

**Pull request merged**
